### ISSUE TITLE
在验证时报错：stack expects each tensor to be equal size, but got [19961] at entry 0 and [123389] at entry 1

### ISSUE THREAD

**Issue by myself0816** [ICEORY/PMF#29]
具体情况如下;
===init env success===
Traceback (most recent call last):
  File "/home/lcy/桌面/PMF-master/tasks/pmf_eval_semantickitti/infer.py", line 369, in <module>
    exp.run()
  File "/home/lcy/桌面/PMF-master/tasks/pmf_eval_semantickitti/infer.py", line 354, in run
    self.inference.run()
  File "/home/lcy/桌面/PMF-master/tasks/pmf_eval_semantickitti/infer.py", line 134, in run
    self.evaluator.addBatch(
  File "/home/lcy/桌面/PMF-master/tasks/pmf_eval_semantickitti/../../pc_processor/metrics/iou_eval.py", line 44, in addBatch
    idxs = torch.stack([x_row, y_row], dim=0)
RuntimeError: stack expects each tensor to be equal size, but got [19961] at entry 0 and [123389] at entry 1

Process finished with exit code 1

请问该如何修改呢？

**Comment by myself0816** [comment]
已经解决了，原因是没有做fov的数据预处理。

**Comment by birdsheng** [comment]
> 已经解决了，原因是没有做fov的数据预处理。

你好，遇到了和你同样的问题，请问这个fov数据预处理在哪里改啊，应该如何修改程序啊？

**Comment by dafengtian** [comment]
> > 已经解决了，原因是没有做fov的数据费用。
> 
> 你好，遇到了和你同样的问题，请问这个数据丢失在哪里改啊，应该如何修改程序啊？

> 你好，这个地方错误是因为没有使用PMF-master > tasks > process_semantickitti_fov制作fov数据集。具体如下：

1.进入tasks/process_semantickitti_fov目录，修改create_fov_dataset.pu文件中数据集路径src_root为semantic-kitti实际路径
![image](https://github.com/ICEORY/PMF/assets/100512884/1cf969ae-6127-4584-aaf0-0fab3aa72661)

2.运行如下指令执行构建semantic-kitti-fov数据集
python create_fov_dataset.py

数据集生成成功，即可正常运行
